"""auto update

Revision ID: 2cf6ab9db7d2
Revises: cdfd06123908
Create Date: 2026-04-23 05:06:38.148442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf6ab9db7d2'
down_revision: Union[str, Sequence[str], None] = 'cdfd06123908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('explanation_ru', sa.String(), nullable=True),
    sa.Column('explanation_kz', sa.String(), nullable=True),
    sa.Column('examples', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_rules_id'), 'grammar_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grammar_rules_id'), table_name='grammar_rules')
    op.drop_table('grammar_rules')
    # ### end Alembic commands ###